# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: kvmukilan.livewire
PackageVersion: 1.2.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: livewire.exe
    PortableCommandAlias: livewire
Commands:
  - livewire
ReleaseDate: 2026-10-01
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/kvmukilan/livewire/releases/download/v1.2.0/livewire-1.2.0-windows-amd64.zip
    InstallerSha256: 58706F17C341226A9401AF678E93E82106F101241F3071669B4A7B5BEDBE933B
ManifestType: installer
ManifestVersion: 1.6.0
